name: Cross-Platform GUI Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Linux setup
    - name: Setup Xvfb (Linux)
      if: runner.os == 'Linux'
      uses: GabrielBB/xvfb-action@v1
      with:
        run: echo "Xvfb configured"

    # macOS setup
    - name: Install XQuartz (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install --cask xquartz
        /opt/X11/bin/Xvfb :99 -ac -screen 0 1024x768x8 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    # Windows setup (no Xvfb needed)
    - name: Configure Windows display
      if: runner.os == 'Windows'
      run: echo "Windows requires no X server configuration"

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    # Test execution
    - name: Run tests
      run: npm test
      env:
        # Required for macOS/Linux GUI tests
        DISPLAY: ${{ runner.os == 'macOS' && ':99' || runner.os == 'Linux' && ':99' }}
