name: Build, Test, and Publish VS Code Extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Linux-specific X server setup
    - name: Configure Linux X Server
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb dbus-x11
        echo "DISPLAY=:99" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 >/dev/null 2>&1 &
        export XDG_RUNTIME_DIR=/run/user/$(id -u)
        export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
        dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile &

    # macOS X server setup
    - name: Configure macOS X Server
      if: runner.os == 'macOS'
      run: |
        brew install --cask xquartz
        /opt/X11/bin/Xvfb :99 -ac -screen 0 1024x768x8 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      env:
        DISPLAY: ${{ runner.os == 'macOS' && ':99' || runner.os == 'Linux' && ':99' }}
        XDG_RUNTIME_DIR: /run/user/$(id -u)
        DBUS_SESSION_BUS_ADDRESS: unix:path=$XDG_RUNTIME_DIR/bus
        ELECTRON_OZONE_PLATFORM_HINT: "x11"
      run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm ci

    - name: Package Extension
      run: vsce package

    - name: Publish to Marketplace
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VSCE_PAT }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: '*.vsix'
